import './globals.css'
import NextThemeProvider from '../providers/NextThemeProvider'
import type { Metadata } from 'next'
import MainLayout from '../components/MainLayout'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body>
        <NextThemeProvider>
          <MainLayout>{children}</MainLayout>
        </NextThemeProvider>
      </body>
    </html>
  )
}
