import './globalLight.css'
import './globalDark.css'
import NextThemeProvider from '../providers/NextThemeProvider'
import { ThemeSwitcher } from '../components/ThemeSwitcher'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body>
        <NextThemeProvider>
          <ThemeSwitcher />
          {children}
        </NextThemeProvider>
      </body>
    </html>
  )
}
